export const AuditCategory = {
  AUTH: 'auth',
  USER_MANAGEMENT: 'user_management',
  DATASOURCE: 'datasource',
  WORKFLOW: 'workflow',
  KNOWLEDGE: 'knowledge',
  SYSTEM_CONFIG: 'system_config',
} as const;

export type AuditCategoryValue = (typeof AuditCategory)[keyof typeof AuditCategory];

export const AuditAction = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_LOCKED: 'USER_LOCKED',
  USER_UNLOCKED: 'USER_UNLOCKED',
  USER_DELETED: 'USER_DELETED',
  DATASOURCE_CREATED: 'DATASOURCE_CREATED',
  DATASOURCE_UPDATED: 'DATASOURCE_UPDATED',
  DATASOURCE_DELETED: 'DATASOURCE_DELETED',
  WORKFLOW_CREATED: 'WORKFLOW_CREATED',
  WORKFLOW_UPDATED: 'WORKFLOW_UPDATED',
  WORKFLOW_DELETED: 'WORKFLOW_DELETED',
  WORKFLOW_EXECUTED: 'WORKFLOW_EXECUTED',
  KNOWLEDGE_FOLDER_CREATED: 'KNOWLEDGE_FOLDER_CREATED',
  KNOWLEDGE_FOLDER_DELETED: 'KNOWLEDGE_FOLDER_DELETED',
  KNOWLEDGE_FILE_UPLOADED: 'KNOWLEDGE_FILE_UPLOADED',
  KNOWLEDGE_FILE_DELETED: 'KNOWLEDGE_FILE_DELETED',
  GLOBAL_CONFIG_UPDATED: 'GLOBAL_CONFIG_UPDATED',
  AUDIT_LOGS_CLEANED: 'AUDIT_LOGS_CLEANED',
} as const;

export type AuditActionValue = (typeof AuditAction)[keyof typeof AuditAction];

export const ACTION_CATEGORY_MAP: Record<AuditActionValue, AuditCategoryValue> = {
  LOGIN_SUCCESS: AuditCategory.AUTH,
  LOGIN_FAILED: AuditCategory.AUTH,
  LOGOUT: AuditCategory.AUTH,
  PASSWORD_CHANGED: AuditCategory.AUTH,
  USER_CREATED: AuditCategory.USER_MANAGEMENT,
  USER_UPDATED: AuditCategory.USER_MANAGEMENT,
  USER_LOCKED: AuditCategory.USER_MANAGEMENT,
  USER_UNLOCKED: AuditCategory.USER_MANAGEMENT,
  USER_DELETED: AuditCategory.USER_MANAGEMENT,
  DATASOURCE_CREATED: AuditCategory.DATASOURCE,
  DATASOURCE_UPDATED: AuditCategory.DATASOURCE,
  DATASOURCE_DELETED: AuditCategory.DATASOURCE,
  WORKFLOW_CREATED: AuditCategory.WORKFLOW,
  WORKFLOW_UPDATED: AuditCategory.WORKFLOW,
  WORKFLOW_DELETED: AuditCategory.WORKFLOW,
  WORKFLOW_EXECUTED: AuditCategory.WORKFLOW,
  KNOWLEDGE_FOLDER_CREATED: AuditCategory.KNOWLEDGE,
  KNOWLEDGE_FOLDER_DELETED: AuditCategory.KNOWLEDGE,
  KNOWLEDGE_FILE_UPLOADED: AuditCategory.KNOWLEDGE,
  KNOWLEDGE_FILE_DELETED: AuditCategory.KNOWLEDGE,
  GLOBAL_CONFIG_UPDATED: AuditCategory.SYSTEM_CONFIG,
  AUDIT_LOGS_CLEANED: AuditCategory.SYSTEM_CONFIG,
};
