/**
 * OutputMd Tool for outputting GitHub-flavored Markdown data analysis reports
 */

import { promises as fs } from 'fs';
import { Tool, ToolRegistry } from './tools';
import { JSONSchemaObject, ToolParams, ToolResult, ToolName } from './types';
import logger from '../../utils/logger';
import { ToolExecutionError } from '../../errors/types';
import {
  validateFilePath,
  extractPlaceholders,
  processFilePlaceholders,
  MAX_FILE_SIZE,
} from '../../utils/markdownProcessor';

/** Maximum content size in bytes (10MB) */
const MAX_CONTENT_SIZE = 10 * 1024 * 1024;

export class OutputMdTool extends Tool {
  name = ToolName.OutputMd;
  description = `Output a GitHub-flavored Markdown data analysis report.
If the user specifies the report format, please be sure to output the report according to the format specified by the user.

The report can include:
- Data tables from CSV files
- Interactive Plotly charts from JSON files (generated by plotly's fig.write_json())
- Mermaid diagrams
- Text descriptions

File placeholders in the format <!-- {/path/to/file} --> can be used to reference files that will be validated.`;

  parameters: JSONSchemaObject = {
    type: 'object',
    properties: {
      md_content: {
        type: 'string',
        description:
          'GitHub-flavored Markdown report content. Can include file placeholders in the format <!-- {/path/to/file} -->',
      },
      replace_files: {
        type: 'array',
        items: { type: 'string' },
        description:
          'Absolute paths of files referenced in placeholders. Each placeholder must have a corresponding file.',
      },
    },
    required: ['md_content'],
  };

  /**
   * Validate tool parameters
   */
  validate(params: ToolParams): boolean {
    if (
      params.md_content === undefined ||
      params.md_content === null ||
      typeof params.md_content !== 'string'
    ) {
      return false;
    }

    if (params.replace_files !== undefined && params.replace_files !== null) {
      if (!Array.isArray(params.replace_files)) {
        return false;
      }
      for (const file of params.replace_files) {
        if (typeof file !== 'string') {
          return false;
        }
      }
    }

    return true;
  }

  /**
   * Execute the OutputMd tool
   * @param params - Tool parameters containing md_content and optional replace_files
   * @returns ToolResult with the markdown content and metadata
   * @throws ToolExecutionError if validation or file checks fail
   */
  async execute(params: ToolParams): Promise<ToolResult> {
    const mdContent = params.md_content as string;
    const replaceFiles = (params.replace_files as string[] | undefined) ?? [];

    // Validate parameters
    if (!this.validate(params)) {
      throw new ToolExecutionError('Invalid parameters');
    }

    // Check for empty content
    if (mdContent.trim() === '') {
      throw new ToolExecutionError('md_content cannot be empty or whitespace only');
    }

    // Check content size
    const contentBytes = Buffer.byteLength(mdContent, 'utf-8');
    if (contentBytes > MAX_CONTENT_SIZE) {
      throw new ToolExecutionError(
        `Content size (${contentBytes} bytes) exceeds maximum allowed (${MAX_CONTENT_SIZE} bytes)`
      );
    }

    // Auto-detect file placeholders from content when replace_files not provided by LLM
    if (replaceFiles.length === 0) {
      const detected = extractPlaceholders(mdContent);
      if (detected.length > 0) {
        replaceFiles.push(...detected);
        logger.info('Auto-detected file placeholders', { count: detected.length });
      }
    }

    // If still no files to replace, return content directly
    if (replaceFiles.length === 0) {
      logger.info('OutputMdTool executed with no file replacements');
      return {
        success: true,
        data: mdContent,
        metadata: {
          parameters: params,
          hasFileReplacements: false,
          contentSize: contentBytes,
          mdContent,
        },
      };
    }

    // Check for forbidden path patterns in replace_files
    for (const filePath of replaceFiles) {
      validateFilePath(filePath);
    }

    // Verify all files exist — skip missing files instead of throwing
    const validFiles: string[] = [];
    for (const filePath of replaceFiles) {
      try {
        await fs.access(filePath);
        validFiles.push(filePath);
      } catch {
        logger.warn(`File not found, skipping placeholder: ${filePath}`);
      }
    }

    // Read all files and build a content map, tracking skipped/replaced files
    const replacedFiles: string[] = [];
    const skippedFiles: string[] = [];
    const fileContentMap = new Map<string, Buffer>();

    for (const filePath of validFiles) {
      const ext = filePath.split('.').pop()?.toLowerCase();
      const isSupportedExt =
        ext === 'csv' ||
        ext === 'json' ||
        ext === 'png' ||
        ext === 'jpg' ||
        ext === 'jpeg' ||
        ext === 'gif' ||
        ext === 'svg';

      if (!isSupportedExt) {
        skippedFiles.push(filePath);
        logger.warn(`Unsupported file type for replacement: ${filePath}`);
        continue;
      }

      try {
        const stats = await fs.stat(filePath);
        if (stats.size > MAX_FILE_SIZE) {
          throw new ToolExecutionError(
            `File size (${stats.size} bytes) exceeds maximum allowed (${MAX_FILE_SIZE} bytes): ${filePath}`
          );
        }

        const fileContent = await fs.readFile(filePath);
        fileContentMap.set(filePath, fileContent);
        replacedFiles.push(filePath);
      } catch (error) {
        if (error instanceof ToolExecutionError) {
          throw error;
        }
        throw new ToolExecutionError(
          `Failed to read file for replacement: ${filePath}`,
          error instanceof Error ? error : undefined
        );
      }
    }

    // Delegate file-to-markdown replacement to shared utility
    const processedContent = processFilePlaceholders(mdContent, fileContentMap);

    const processedContentBytes = Buffer.byteLength(processedContent, 'utf-8');
    logger.info(
      `OutputMdTool executed with ${replacedFiles.length} file replacements, ${skippedFiles.length} skipped`
    );

    return {
      success: true,
      data: mdContent,
      metadata: {
        parameters: params,
        hasFileReplacements: replacedFiles.length > 0,
        replaceFiles: replacedFiles,
        skippedFiles: skippedFiles.length > 0 ? skippedFiles : undefined,
        contentSize: processedContentBytes,
        mdContent: processedContent,
      },
    };
  }
}

// Register the OutputMd tool instance
ToolRegistry.register(new OutputMdTool());
